languageCode = 'zh-CN'
title = "Siyang's Blog"
theme = 'yinyang'

[params]
headTitle = 'Siyang Z'

[[params.socials]]
name = "Github"
link = "https://github.com/Zhang-Siyang"

[[params.socials]]
name = "IG"
link = "https://www.instagram.com/siyang_zhang_/"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[markup.highlight]
style = "xcode"

[services]
  [services.googleAnalytics]
    id = 'G-JW48W178T1'

[module]
  [[module.mounts]]
    source = 'content-tech'
    target = 'content/posts'
  [[module.mounts]]
    source = 'content-life'
    target = 'content/posts'