baseURL = 'https://sy.netlify.app/'
languageCode = 'zh-CN'
title = "Siyang's Blog"
theme = 'yinyang'

[params]
headTitle = 'Siyang Z'
extraHead = '''
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-JW48W178T1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-JW48W178T1');
</script>'''

[[params.socials]]
name = "Github"
link = "https://github.com/Zhang-Siyang"

[[params.socials]]
name = "IG"
link = "https://www.instagram.com/siyang_zhang_/"

[markup.highlight]
style = "xcode"
codeFences = true
lineNos = "inline"
