baseURL = 'https://sy.netlify.app/'
languageCode = 'zh-CN'
title = "Siyang's Blog"
theme = 'yinyang'

[params]
headTitle = 'Siyang Z'

[[params.socials]]
name = "Github"
link = "https://github.com/Zhang-Siyang"

[[params.socials]]
name = "IG"
link = "https://www.instagram.com/siyang_zhang_/"

[markup.highlight]
style = "xcode"
codeFences = true
lineNos = "inline"
